version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "MyPass123"
    MYSQL_ROOT_PASSWORD: "MyPass123"
  panel:
    &panel-environment
    # This URL should be the URL that your reverse proxy routes to the panel server
    #APP_URL: "https://pterodactyl.example.com"
    APP_URL: ${PTERO_FQDN}
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: ${PTERO_TZ}
    APP_SERVICE_AUTHOR: "my email@gmail.com"

services:
  wings:
    container_name: pterodactyl-wings-1
    image: ghcr.io/pterodactyl/wings:${VERSION}
    restart: always
    networks:
      - ptero-wings
    ports:
      - ${PTERO_WINGS_API_PORT}:${PTERO_WINGS_API_PORT}/tcp
      - ${PTERO_WINGS_SFTP_PORT}:${PTERO_WINGS_SFTP_PORT}/tcp
    tty: true
    environment:
      TZ: ${PTERO_TZ}
      WINGS_UID: 970
      WINGS_GID: 970
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers"

      - "/var/lib/pterodactyl:/var/lib/pterodactyl"
      - "/var/log/pterodactyl:/var/log/pterodactyl"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"

      - ${PTERO_ROOT}/certs/:/etc/letsencrypt/
      - ${PTERO_ROOT}/wings/etc:/etc/pterodactyl/

  database:
    container_name: pterodactyl-panel-database
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${PTERO_ROOT}/database:/var/lib/mysql
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    container_name: pterodactyl-panel-cache
    image: redis:alpine
    restart: always

  panel:
    container_name: pterodactyl-panel
    image: ghcr.io/pterodactyl/panel:${VERSION}
    restart: always
    ports:
      - ${PTERO_HTTP_PORT}:80/tcp
      - ${PTERO_HTTPS_PORT}:443/tcp
    links:
      - database
      - cache
    volumes:
      - ${PTERO_ROOT}/var/:/app/var/
      - ${PTERO_ROOT}/nginx/:/etc/nginx/http.d/
      - ${PTERO_ROOT}/certs/:/etc/letsencrypt/
      - ${PTERO_ROOT}/logs/:/app/storage/logs
    environment:
#      <<: [*panel-environment, *mail-environment]
      <<: [*panel-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

networks:
  ptero-wings:
    name: ptero-wings
    driver: bridge
    ipam:
      config:
        - subnet: "192.55.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: ptero-wings
